### ISSUE TITLE
If product links are removed, then added later, the new links don't appear in invoice

### ISSUE THREAD

**Issue by b-d-m-p** [ProxiBlue/UpdateDownloadLinks#1]
Hi, 

Thank you for the great extension.

I have an issue where if I have a product with a download link, delete it, and save it, then later if I add one back, it doesn't appear in invoices. Basically, as long as you already have a link and update or add another it is fine. But if you take them all away, save and try to re-add them, the invoices won't update.

Is this behavior consistent with your experience? 

Thanks.

**Comment by ProxiBlue** [comment]
I have not tested this, as the usage case has not occurred.
I will test for this and see if I can solve this.
