### ISSUE TITLE
StackOverflow "bug fix": is it necessary?

### ISSUE THREAD

**Issue by b-d-m-p** [ProxiBlue/UpdateDownloadLinks#2]
Hi,

I was just curious about the issues that this StackOverflow post, which you commented on. 

http://stackoverflow.com/questions/17468869/how-to-update-new-downloadable-product-attachment-for-placed-orders-in-magento

I tried the "bug fix" that the man mentions, but the script stops working. Do you think the things that he is talking about are of concern?

Thanks.

**Comment by ProxiBlue** [comment]
Hi,

It all depends on requirements. For my own use (currently) it is not a concern to loose the download history, as it is not used by the site for which this code was originally created.

If, however, you limit your clients to download the files X times, you will (currently) loose the history count of their downloads, thus the limit cannot effetively be applied, as any update will reset the count back to 0)

In regards to the 'not paid' remark: this could be an issue if you have orders created that can be in a Payment Pending status. (have not tested this as the site this was created for cannot have those)

I did ask for the person to create a pull request here with their changes, but they have not yet done so.
I will try and have a look at their changes in the near future, when my schedule relaxes a bit. very busy with paid for modules and support/work, so the free stuff do lag a bit (unfortunately)
